[project]
name = "fastmcp-playground"
version = "0.1.0"
description = "A playground to test and develop an MCP server with FastMCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
